# 1. Create a file called Dockerfile, and add content to it as described below.
# our base image
FROM alpine:3.5

# 2. The next step usually is to write the commands of copying the files 
#    and installing the dependencies. But first we will install the Python 
#    pip package to the alpine linux distribution. 
#    This will not just install the pip package but any other dependencies too, 
#    which includes the python interpreter. Add the following RUN command next:
# Install python and pip
RUN apk add --update py2-pip

# 3. Let's add the files that make up the Flask Application.

# Install all Python requirements for our app to run. 
# This will be accomplished by adding the lines:
# install Python modules needed by the Python app
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt

# Copy the files you have created earlier into our image by using COPY command.
# copy files required for the app to run
COPY app.py /usr/src/app/
COPY templates/index.html /usr/src/app/templates/

# 4. Specify the port number which needs to be exposed. 
#    Since our flask app is running on 5000 that's what we'll expose.
# tell the port number the container should expose
EXPOSE 5000

# 5. The last step is the command for running the application 
#    which is simply - python ./app.py. Use the CMD command to do that:
# run the application
CMD ["python", "/usr/src/app/app.py"]